### ISSUE TITLE
Logge hvilke topics som blir replikert

### ISSUE THREAD

**Issue by androa** [nais/aivia#1]
Det hadde vært veldig fint å fått med navnet på topicene når noe blir replikert. Nå sier den bare `Found 3 records to mirror` og når det er mange muligheter er ikke så lett å debugge.

**Comment by mortenlj** [comment]
Tenker du da at den burde logge for hver melding den replikerer, eller antall per topic i hver bolk?

**Comment by androa** [comment]
Nå logger den noe som 
```
INFO  io.nais.aivia.Aivia - Found 2 records to mirror
```

Det hadde vært betryggende å også se hvilke topics den replikerer meldinger for.
