### ISSUE TITLE
Feil format i apploggen?

### ISSUE THREAD

**Issue by ahusby** [nais/aivia#20]
Det ser ut som at [formatet på loggingen til apploggen](https://github.com/nais/aivia/blob/main/src/main/resources/log4j2.xml#L5) avviker fra [nais-dokumentasjonen](https://doc.nais.io/observability/logs/examples/#log4j2xml),  og det ser rart ut i apploggen til [min instans av Aivia](https://github.com/navikt/rekrutteringsbistand-stilling-kafkabro): Når jeg søker på https://logs.adeo.no/app/discover i `logstash-apps-*` med `envclass : "p" and application : "rekrutteringsbistand-stilling-kafkabro" ` så er det ingen verdi i feltet `level` og jeg ser at loglevel og timestamp er inneholdt i feltet `message`. Prøver å legge ved screenshot.
![image](https://user-images.githubusercontent.com/12073037/215505451-e42adfdb-3e93-45e2-88a3-e44874cf42bf.png)

**Comment by jksolbakken** [comment]
Ser ut som de bare har glemt å legge på ```
env:
    - name: LOG_FORMAT
      value: logstash
```
y yaml-en sin
