### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by mortenlj** [nais/aivia#5]
Noen tester feiler innimellom på GHA. En re-run fikser det. Disse bør sees på slik at de blir mer robuste.

**Comment by mortenlj** [comment]
Maybe Fixed in c7dc9f2

**Comment by mortenlj** [comment]
Still flaky

**Comment by jksolbakken** [comment]
Tried to use structured CoroutineScopes to make everything shut down in the right order, but something ™ keeps the coroutines stuck in the "cancelling" state. I suspect that the Kafka libs do something weird with threads

**Comment by mortenlj** [comment]
Prøver meg på noen eksplisitte kall til `close` med en timeout, kanskje det løser problemet.
`close` skal i utgangspunktet bli kalt allerede, men uten en timeout. Da kan de i teorien bli stående i `Long.MAX_VALUE` sekunder, som kan være litt lenge å vente ...
